version: 2

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:lts

jobs:
  lint:
    <<: *defaults

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: 
          name: ESLint
          command: yarn lint

  test:
    <<: *defaults

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: 
          name: Jest
          command: yarn test --reporters=default --reporters=jest-junit
          environment:
                  JEST_JUNIT_OUTPUT_DIR: "test-results/jest/results.xml"

      - run:
          name: Upload coverage report
          command: yarn test:codecov

      - store_test_results:
          path: test-results

  build:
    <<: *defaults

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: yarn test
      - run: yarn build

      - persist_to_workspace:
          root: ~/repo
          paths: 
            - .

  release:
    <<: *defaults

    steps:
      - attach_workspace:
          at: ~/repo

      - run:
          name: Semantic release
          command: yarn semantic-release

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - test
      - lint
      - build
      - approve:
          type: approval
          requires:
            - test
            - lint
            - build
          filters:
            branches:
              only: master
      - release:
          requires:
            - approve
              